In [4]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder
#from sklearn.compose import ColumnTransfomer
#from sklearn.pipeline import pipeline
#from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest, f_regression,f_classif
#from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder

df =pd.read_csv("auto-mpg.csv")
display(df.head())

    mpg  cylinders  displacement  ... model year  origin                   car name
0  18.0          8         307.0  ...         70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...         70       1          buick skylark 320
2  18.0          8         318.0  ...         70       1         plymouth satellite
3  16.0          8         304.0  ...         70       1              amc rebel sst
4  17.0          8         302.0  ...         70       1                ford torino

[5 rows x 9 columns]

In [5]:
# To automatically find numeric columns:
numeric_columns=df.select_dtypes(include=np.number).columns

print("Numeric Columns:")
print(numeric_columns)

#origin is often represented by numbers such as 1,2,3,
#so techinally pandas may identify it as numeric
#even though it represents categories.

Numeric Columns:
Index(['mpg', 'cylinders', 'displacement', 'weight', 'acceleration',
       'model year', 'origin'],
      dtype='object')

In [6]:
# To automatically find categorical columns:
categorical_columns=df.select_dtypes(include="object").columns

print("Categorical Columns:")
print(categorical_columns)

Categorical Columns:
Index(['horsepower', 'car name'], dtype='object')

In [7]:
#first check missing values:
print(df.isnull().sum())

# Auto-MPG commonly represent missing horespower value using ?.
# So first convert ? into  missing value

df=df.replace("?",np.nan)
print(df.isnull().sum())

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64
mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [8]:
# Convert horsepower to numeric
df["horsepower"]=pd.to_numeric(df["horsepower"])

#handel missing values in horse power
df["horsepower"]=df["horsepower"].fillna(df["horsepower"].mean())

print(df.isnull().sum())

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [9]:
scaler=MinMaxScaler().set_output(transform="pandas")

scaled_data=scaler.fit_transform(df[numeric_columns])

scaled_data.head()

        mpg  cylinders  displacement  ...  acceleration  model year  origin
0  0.239362        1.0      0.617571  ...      0.238095         0.0     0.0
1  0.159574        1.0      0.728682  ...      0.208333         0.0     0.0
2  0.239362        1.0      0.645995  ...      0.178571         0.0     0.0
3  0.186170        1.0      0.609819  ...      0.238095         0.0     0.0
4  0.212766        1.0      0.604651  ...      0.148810         0.0     0.0

[5 rows x 7 columns]

In [11]:
categorical_columns=["origin","car name"]

#OHE

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
).set_output(transform="pandas")

encoded_data=encoder.fit_transform(df[categorical_columns])
display(encoded_data.head())

   origin_1  origin_2  ...  car name_vw rabbit c (diesel)  car name_vw rabbit custom
0       1.0       0.0  ...                            0.0                        0.0
1       1.0       0.0  ...                            0.0                        0.0
2       1.0       0.0  ...                            0.0                        0.0
3       1.0       0.0  ...                            0.0                        0.0
4       1.0       0.0  ...                            0.0                        0.0

[5 rows x 308 columns]

In [15]:
#suppose mpg is our traget
x=df.drop("mpg",axis=1)
y=df["mpg"]

In [16]:
display(y)

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [17]:
display(x)

     cylinders  displacement  ...  origin                   car name
0            8         307.0  ...       1  chevrolet chevelle malibu
1            8         350.0  ...       1          buick skylark 320
2            8         318.0  ...       1         plymouth satellite
3            8         304.0  ...       1              amc rebel sst
4            8         302.0  ...       1                ford torino
..         ...           ...  ...     ...                        ...
393          4         140.0  ...       1            ford mustang gl
394          4          97.0  ...       2                  vw pickup
395          4         135.0  ...       1              dodge rampage
396          4         120.0  ...       1                ford ranger
397          4         119.0  ...       1                 chevy s-10

[398 rows x 8 columns]

In [23]:
# For a sample numerical example,we can select the best 5 features:

x_numeric =x.select_dtypes(include=np.number)

selector=SelectKBest(
    score_func=f_regression,
    k=5
).set_output(transform="pandas")

x_selected=selector.fit_transform(x_numeric,y)
print(x_selected.head())

   cylinders  displacement  horsepower  weight  model year
0          8         307.0       130.0    3504          70
1          8         350.0       165.0    3693          70
2          8         318.0       150.0    3436          70
3          8         304.0       150.0    3433          70
4          8         302.0       140.0    3449          70

In [25]:
# For a sample numerical example,we can select the best 5 features:

x_final=pd.concat([encoded_data,x_selected],axis=1)
#axis=1 means column

selector=SelectKBest(
    score_func=f_regression,
    k=5
).set_output(transform="pandas")

x_selected=selector.fit_transform(x_final,y)
print(x_selected.head())

   cylinders  displacement  horsepower  weight  model year
0          8         307.0       130.0    3504          70
1          8         350.0       165.0    3693          70
2          8         318.0       150.0    3436          70
3          8         304.0       150.0    3433          70
4          8         302.0       140.0    3449          70